name: Push Backend to Hugging Face

on:
  push:
    paths:
      - 'backend/**'
    branches:
      - main
  workflow_dispatch:  # Allows the workflow to be manually triggered

jobs:
  push-to-hf:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Initialize and Push to Hugging Face
        run: |
          cd backend
          git init
          git branch -m main  # Rename the branch from 'master' to 'main'
          git remote add origin https://huggingface.co/spaces/unipalmark/backend
          git add .
          git commit -m "Initial commit"
          git push origin main --force  # Push to the 'main' branch
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
